name: miapp
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0 # Fuentes de Google
  get: ^4.6.6

  #flutter_native_splash: ^2.3.3 # Flutter Splash

#flutter_native_splash:
 # color: "#f7f6f1"
 # color_dark: "#272727"
#  image: assets/images/tadeotaxtm.png
#  image_dark: assets/images/tadeotaxtm.png

 # android_12:
  #  image: assets/images/tadeotaxtm.png
  #  icon_background_color: "#f7f6f1"
  #  image_dark: assets/images/tadeotaxtm.png
  #  icon_background_color_dark: "#272727"

dev_dependencies:
  flutter_test:
    sdk: flutter


  
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  
  assets:
  - assets/images/
  - assets/images/welcome_images/
# Logos
  - assets/logo/
# Forget Password
  - assets/images/forget_password/
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
